import logging
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, CallbackQueryHandler, ContextTypes

TOKEN = "U8736534442:AAFUqolj_G7xcIhhSOVEeeRLWiQZYEFP2XQ"          # Se cambiará después en Railway
ADMIN_ID = 5793886850             # Se cambiará después en Railway

COMPROBANTE_PATH = "comprobante.jpg"

logging.basicConfig(level=logging.INFO)
solicitudes = {}

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
            "👋 ¡Bienvenido al bot de comprobantes!\n\n"
                    "Para solicitar un comprobante escribe:\n"
                            "/solicitar [monto]\n"
                                    "Ejemplo: /solicitar 50"
                                        )

                                        async def solicitar(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                            if not context.args:
                                                    await update.message.reply_text("❌ Uso correcto: /solicitar [monto]\nEjemplo: /solicitar 100")
                                                            return
                                                                try:
                                                                        monto = float(context.args[0])
                                                                                user_id = update.effective_user.id
                                                                                        username = update.effective_user.username or update.effective_user.first_name

                                                                                                solicitudes[user_id] = {"monto": monto, "username": username}

                                                                                                        await update.message.reply_text(
                                                                                                                    f"✅ Solicitud recibida por **${monto}**\n\n"
                                                                                                                                f"Debes pagarme **5 veces** ese monto → **${monto * 5}**\n\n"
                                                                                                                                            f"Cuando hayas pagado, escribe **/pagado** para avisarme."
                                                                                                                                                    )

                                                                                                                                                            keyboard = [
                                                                                                                                                                        [InlineKeyboardButton("✅ Confirmar pago y enviar comprobante", callback_data=f"confirm_{user_id}")],
                                                                                                                                                                                    [InlineKeyboardButton("❌ Rechazar solicitud", callback_data=f"reject_{user_id}")]
                                                                                                                                                                                            ]
                                                                                                                                                                                                    reply_markup = InlineKeyboardMarkup(keyboard)

                                                                                                                                                                                                            await context.bot.send_message(
                                                                                                                                                                                                                        chat_id=ADMIN_ID,
                                                                                                                                                                                                                                    text=f"🛎️ **Nueva solicitud**\n\nUsuario: @{username}\nMonto: ${monto}\nA pagar: ${monto*5}",
                                                                                                                                                                                                                                                reply_markup=reply_markup,
                                                                                                                                                                                                                                                            parse_mode="Markdown"
                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                        except ValueError:
                                                                                                                                                                                                                                                                                await update.message.reply_text("❌ El monto debe ser un número.")

                                                                                                                                                                                                                                                                                async def pagado(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                    if update.effective_user.id in solicitudes:
                                                                                                                                                                                                                                                                                            await update.message.reply_text("✅ Aviso recibido. Estoy verificando el pago manualmente...")
                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                        await update.message.reply_text("❌ No tienes ninguna solicitud pendiente.")

                                                                                                                                                                                                                                                                                                        async def button_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                                                            query = update.callback_query
                                                                                                                                                                                                                                                                                                                await query.answer()
                                                                                                                                                                                                                                                                                                                    data = query.data

                                                                                                                                                                                                                                                                                                                        if data.startswith("confirm_"):
                                                                                                                                                                                                                                                                                                                                user_id = int(data.split("_")[1])
                                                                                                                                                                                                                                                                                                                                        if user_id in solicitudes:
                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                    with open(COMPROBANTE_PATH, "rb") as photo:
                                                                                                                                                                                                                                                                                                                                                                                        await context.bot.send_photo(
                                                                                                                                                                                                                                                                                                                                                                                                                chat_id=user_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                        photo=photo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                caption="✅ Pago verificado correctamente.\nAquí tienes tu comprobante de transferencia."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await query.edit_message_text("✅ Comprobante enviado al usuario.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    del solicitudes[user_id]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await query.edit_message_text(f"❌ Error al enviar foto: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    elif data.startswith("reject_"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            user_id = int(data.split("_")[1])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await context.bot.send_message(user_id, "❌ Tu solicitud fue rechazada.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await query.edit_message_text("❌ Solicitud rechazada.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if user_id in solicitudes:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                del solicitudes[user_id]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    application = Application.builder().token(TOKEN).build()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        application.add_handler(CommandHandler("start", start))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            application.add_handler(CommandHandler("solicitar", solicitar))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                application.add_handler(CommandHandler("pagado", pagado))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    application.add_handler(CallbackQueryHandler(button_callback))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("🤖 Bot iniciado correctamente en Railway")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            application.run_polling(drop_pending_updates=True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main()